## Tablas para reporte Portafolio Excel B

In [1]:
#Imports

# Analisis de datos
import datetime as dt
import pandas as pd

#Importar informacion de Yahoo Finance
import yfinance as yf

In [2]:
# Dates para todo el proceso
start_date = "2019-12-01"
end_date = dt.date.today()

In [3]:
# Definir Tickers del portafolio
tickers = ["IVV", "VEA", "VCIT", "VGSH", "VGIT", 
           "TIP", "VWO", "SHV" ]

In [4]:
# Bajar la info de Yahoo finance para el rango de Datos Definido
data = yf.download(tickers,  start = start_date , end = end_date)

# Usar closing price
df = data.Close

# Round numbers a dos decimales
df = df.round(2)

# Checando la tabla
print("Start Date: ", start_date)
print("End Date:   ", end_date)
print("")

df.tail()

[*********************100%***********************]  8 of 8 completed
Start Date:  2019-12-01
End Date:    2022-01-11

               IVV     SHV     TIP   VCIT    VEA   VGIT   VGSH    VWO
Date
2022-01-04  479.68  110.40  127.97  92.24  51.56  66.15  60.79  49.61
2022-01-05  470.33  110.38  126.93  91.76  51.11  65.93  60.72  48.87
2022-01-06  469.98  110.39  126.38  91.59  50.83  65.78  60.65  49.15
2022-01-07  468.10  110.40  126.23  91.33  51.04  65.65  60.66  49.40
2022-01-10  467.22  110.40  126.39  91.25  50.57  65.61  60.61  49.50

In [5]:
# Filling the missing Price Values with last known values
df.fillna(method='ffill', inplace=True)
df.tail(20)

               IVV     SHV     TIP   VCIT    VEA   VGIT   VGSH    VWO
Date
2021-12-13  467.07  110.42  128.71  93.62  50.61  67.08  61.06  49.46
2021-12-14  463.77  110.42  128.30  93.38  50.35  67.02  61.03  49.35
2021-12-15  471.06  110.41  128.41  93.54  50.97  66.95  61.03  49.17
2021-12-16  466.74  110.43  127.89  93.73  50.98  67.15  61.07  49.30
2021-12-17  462.11  110.42  127.90  93.79  50.39  67.21  61.06  48.96
2021-12-20  456.92  110.41  127.83  93.65  49.38  67.22  61.08  47.81
2021-12-21  465.06  110.42  128.11  93.59  50.00  67.04  61.03  48.62
2021-12-22  469.75  110.42  128.52  93.64  50.51  67.06  61.05  48.89
2021-12-23  472.63  110.42  128.23  92.83  50.82  66.54  60.83  49.18
2021-12-27  479.40  110.42  128.66  92.96  51.21  66.53  60.80  49.34
2021-12-28  479.03  110.41  128.58  92.97  51.21  66.56  60.79  49.17
2021-12-29  479.53  110.42  128.69  92.66  51.20  66.40  60.79  48.96
2021-12-30  478.18  110.42  129.36  92.89  51.08  66.53  60.83  49.59
2021-12-31  476.99  110.42  129.20  92.76  51.06  66.47  60.83  49.46
2022-01-03  479.84  110.40  128.46  92.17  51.37  66.13  60.75  49.81
2022-01-04  479.68  110.40  127.97  92.24  51.56  66.15  60.79  49.61
2022-01-05  470.33  110.38  126.93  91.76  51.11  65.93  60.72  48.87
2022-01-06  469.98  110.39  126.38  91.59  50.83  65.78  60.65  49.15
2022-01-07  468.10  110.40  126.23  91.33  51.04  65.65  60.66  49.40
2022-01-10  467.22  110.40  126.39  91.25  50.57  65.61  60.61  49.50

In [6]:
# Filtering to use the end of month data
#    If a date is missing (row), we will get an error.
#    We use BM (business month)

# Defining a date range where values should exist
SOM_dates = pd.date_range(start=start_date, end=end_date, freq='MS')
EOM_dates = pd.date_range(start=start_date, end=end_date, freq='BM')

# This date has no data. 
# We remove it to get the rest of the list.
EOM_dates = EOM_dates.drop("2021-05-31")

# Filtering in date range
df = df.loc[EOM_dates]

In [7]:
# Save the DataFrame as CSV
# df.to_csv("Precios_Reporte_PortafolioB.csv", index=True)
df.to_csv("/Users/portfedh/Desktop/Precios_Reporte_PortafolioB.csv", index=True)