## Tablas para reporte Portafolio Excel A

In [1]:
#Imports

# Analisis de datos
import datetime as dt
import pandas as pd
#from pandas_datareader import data as pdr

#Importar informacion de Yahoo Finance
import yfinance as yf

In [2]:
# Dates para todo el proceso
start_date = "2021-01-01"
end_date = dt.date.today()

In [3]:
# Definir Tickers del portafolio
tickers = ["VOO", "VUG", "SMEA.MI", "CPXJ.L", "IJPA.L", 
           "EIMI.L", "IBTA.L", "CBU7.L", "IDTP.L", "LQDA.L",
           "AGGU.L", "GDX", "SHV", "EURUSD=X","CSPX.L" ]

In [4]:
# Bajar la info de Yahoo finance para el rango de Datos Definido
data = yf.download(tickers,  start = start_date , end = end_date)

# Usar closing price
df = data.Close

# Cambiar nombres de columnas para que no tengan puntos. 
df = df.rename(columns={ "SMEA.MI":"SMEA_MI", "EURUSD=X":"FX_EURUSD"})

# AÃ±adiendo la columna para SMEA en USD
df["SMEA_USD"] = df.SMEA_MI * df.FX_EURUSD

# Round numbers a dos decimales
df = df.round(2)

# Checando la tabla
print("Start Date: ", start_date)
print("End Date:   ", end_date)
print("")

df.tail()

[*********************100%***********************]  15 of 15 completed
Start Date:  2021-01-01
End Date:    2022-01-11

,AGGU.L,CBU7.L,CPXJ.L,CSPX.L,EIMI.L,FX_EURUSD,GDX,IBTA.L,IDTP.L,IJPA.L,LQDA.L,SHV,SMEA_MI,VOO,VUG,SMEA_USD
Date,,,,,,,,,,,,,,,,
2022-01-05,5.65,137.60,176.16,488.71,35.51,1.13,30.85,5.37,255.42,52.22,6.38,110.38,69.38,430.66,308.23,78.29
2022-01-06,5.64,137.15,172.48,480.19,35.22,1.13,29.76,5.37,252.80,51.28,6.34,110.39,68.38,430.08,307.56,77.36
2022-01-07,5.62,136.84,173.26,477.88,35.41,1.13,30.01,5.37,252.60,50.74,6.30,110.40,68.26,428.59,304.21,77.11
2022-01-10,5.61,NaN,NaN,NaN,35.40,1.14,30.51,5.36,NaN,50.54,6.29,110.40,NaN,428.03,303.59,NaN
2022-01-11,NaN,NaN,NaN,NaN,NaN,1.13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# Filling the missing Price Values with last known values
df.fillna(method='ffill', inplace=True)
df.tail()

,AGGU.L,CBU7.L,CPXJ.L,CSPX.L,EIMI.L,FX_EURUSD,GDX,IBTA.L,IDTP.L,IJPA.L,LQDA.L,SHV,SMEA_MI,VOO,VUG,SMEA_USD
Date,,,,,,,,,,,,,,,,
2022-01-05,5.65,137.60,176.16,488.71,35.51,1.13,30.85,5.37,255.42,52.22,6.38,110.38,69.38,430.66,308.23,78.29
2022-01-06,5.64,137.15,172.48,480.19,35.22,1.13,29.76,5.37,252.80,51.28,6.34,110.39,68.38,430.08,307.56,77.36
2022-01-07,5.62,136.84,173.26,477.88,35.41,1.13,30.01,5.37,252.60,50.74,6.30,110.40,68.26,428.59,304.21,77.11
2022-01-10,5.61,136.84,173.26,477.88,35.40,1.14,30.51,5.36,252.60,50.54,6.29,110.40,68.26,428.03,303.59,77.11
2022-01-11,5.61,136.84,173.26,477.88,35.40,1.13,30.51,5.36,252.60,50.54,6.29,110.40,68.26,428.03,303.59,77.11

In [6]:
# Filtering to use the end of month data
#    If a date is missing (row), we will get an error.
#    We use BM (business month)

# Defining a date range where values should exist
EOM_dates = pd.date_range(start=start_date, end=end_date, freq='BM')

df = df.loc[EOM_dates]
df

,AGGU.L,CBU7.L,CPXJ.L,CSPX.L,EIMI.L,FX_EURUSD,GDX,IBTA.L,IDTP.L,IJPA.L,LQDA.L,SHV,SMEA_MI,VOO,VUG,SMEA_USD
Date,,,,,,,,,,,,,,,,
2021-01-29,5.75,141.50,167.22,377.05,36.86,1.21,34.51,5.42,245.68,50.54,6.46,110.52,54.06,340.18,250.77,65.52
2021-02-26,5.64,139.25,173.08,388.44,37.27,1.22,31.13,5.41,237.63,51.44,6.24,110.52,55.54,349.59,252.89,67.54
2021-03-31,5.64,138.89,174.95,402.94,36.87,1.17,32.50,5.41,240.05,51.82,6.22,110.51,59.14,364.30,257.04,69.33
2021-04-30,5.65,139.50,181.60,423.81,37.53,1.21,34.36,5.42,243.62,51.10,6.27,110.51,60.35,383.57,274.81,73.19
2021-05-31,5.66,140.04,186.98,427.35,38.18,1.22,39.42,5.42,246.26,51.87,6.32,110.51,61.92,386.13,270.88,75.48
2021-06-30,5.69,139.88,182.37,435.94,38.59,1.19,33.98,5.41,248.24,51.34,6.46,110.49,62.99,393.52,286.81,74.97
2021-07-30,5.75,141.18,180.59,446.64,36.52,1.19,34.92,5.42,255.15,51.26,6.55,110.49,64.11,403.15,295.94,76.25
2021-08-31,5.74,140.83,180.80,460.73,37.02,1.18,32.60,5.42,254.80,52.25,6.52,110.47,65.32,415.05,306.81,77.06
2021-09-30,5.68,139.54,173.20,442.62,35.96,1.16,29.47,5.41,252.23,53.47,6.43,110.47,63.37,394.40,290.17,73.52
2021-10-29,5.67,138.43,181.17,468.21,36.10,1.17,31.71,5.39,255.61,51.96,6.46,110.44,66.43,422.16,314.15,77.61
2021-11-30,5.70,138.74,168.03,467.74,34.61,1.13,31.80,5.39,258.10,49.65,6.46,110.39,64.79,419.06,316.39,73.17
2021-12-31,5.68,138.57,174.18,487.33,35.65,1.13,32.03,5.38,259.05,51.06,6.46,110.42,68.47,436.57,320.90,77.78

In [7]:
# Save the DataFrame as CSV
# df.to_csv("Precios_Reporte_Portafolio.csv", index=True)
df.to_csv("/Users/portfedh/Desktop/Precios_Reporte_PortafolioA.csv", index=True)